dictionary_version = ["Olympia G3", "Dictionary of turn #59"]

# there is still the problem with "wood" beeing converted to 77, while still beeing a skill. use COLLECT!

# need to update the whole dict once in a while.. nobles, etc.
# also, 401, 402,403 have been added and not added to the main dictionary yet.

aliaslist = ['_Ivory_Tower', '_Gulpers_Rock', '_Cave', 'accept', 'admit', 'attack', 'banner', 'behind', 'board', 'bribe', 'breed', 'build', 'buy', 'catch', 'claim', 'collect', 'contact', 'decree', 'default', 'defend', 'die', 'drop', 'email', 'execute', 'exhume', 'explore', 'fee', 'ferry', 'fish', 'flag', 'fly', 'forget', 'form', 'format', 'garrison', 'get', 'give', 'guard', 'honor', 'hostile', 'improve', 'lore', 'make', 'message', 'move', 'name', 'neutral', 'notab', 'oath', 'password', 'pay', 'pillage', 'players', 'pledge', 'post', 'press', 'promote', 'public', 'quarry', 'quest', 'quit', 'raze', 'recruit', 'repair', 'research', 'resend', 'rumor', 'sail', 'seek', 'sell', 'sneak', 'stack', 'stop', 'study', 'surrender', 'take', 'terrorize', 'train', 'ungarrison', 'unload', 'unstack', 'use', 'vis_email', 'wait', 'clear', 'day', 'turn', 'ferry', 'flag', 'fog', 'item', 'loc', 'not', 'owner', 'rain', 'ship', 'shiploc', 'stack', 'time', 'top', 'unit', 'wind', 'n', 'north', 's', 'south', 'w', 'west', 'e', 'east', 'in', 'out', 'Boduognat', 'Bullywug', 'Beowulf', 'Empirius', 'Satyr', 'Rudbert', 'Bigstick', 'Myka_Vykos', 'Skullthumper', 'Seven_fingers', 'Igor_the_Bonegrinder', 'Nepomucenos', 'Paolo_Giovanni', 'Mud', 'Frikky', 'Cain', 'Snake', 'Jinx', 'Didude', 'Banana_Nut', 'Dronte', 'Slook', 'Dreg', 'Hammer', 'Eternal', 'Bomber', 'Sloth', 'Glutony', 'Envy', 'Pride', 'Wrath', 'Passage', 'Rebellion', 'Bastard', 'Greed', 'Lust', 'Rakharo', 'Jhogo', 'Jaehaerys_Targaryen', 'Rhaegar_Targaryen', 'Strong_Belwas', 'Aerys_Targaryen', 'Drogo', 'Jorah_Mormont', 'Arstan_Whitebeard', 'Jaehaerys_Targaryen', 'Daenarys_Targaryen', 'Aegon_Targaryen', 'Rhaenys_Targaryen', 'Aemon_Targaryen', 'Jhiqui', 'Viserys_Targaryen', 'Illyrio_Mopatis', 'King_Bockor', 'Grunk', 'Braaggh', 'Korgul', 'Scrag', 'Drakk', 'Mord', 'Karash', 'Karak', 'Murk', 'Oomph', 'Claw', 'Gruumsh', 'Krusk', 'Azuul', 'Harhar', 'Ubada', 'Munguk_the_giant', 'Red_Kraken', 'Primal_Freegrazer', 'Yoshi_the_Gulper', 'Nightfury', 'Wolftail', 'Mighty_Wings', 'Doom_Dreadnaught', 'White_Spear', 'Horror_Show', 'Mouth_of_the_Devourer', 'Hard_Boiled', 'Cat_of_Purr', 'Black_Fangs', 'Feathersnake', 'Silent_Paw', 'Yu-Yu_the_Gloater', 'Totemizer', 'Dangerlight', 'Dread_Frog', 'Painful_Death', 'Souldrinker', 'Grim_Reaper', 'Pestilence', 'Famine', 'Conquest', "Satan's_Little_Helper_II", 'War', "Satan's_Little_Helper", 'Joris', 'Piet', 'David_Livingstone', 'Walking_Death', 'Ethan_Venge', 'Drago_Spatz', 'Sgt_York', 'Karl_Meckler', 'Jason_West', 'Carey_Bridger', 'John_Builder', 'Harlan_Brenach', 'Billy_Mack', 'Joe_Fish', 'Sgt_Rock', 'Jim_Nance', 'Yancy_James', 'Ziggy_Stardust', 'Jorj', 'Godzilla', 'Klaus', 'Jimmy_Dean', 'Emissary', 'Pen', 'Xen', 'Dude', 'Howl', 'Hasan', 'Talin', 'Full_of_Hot_Air', 'Seasick_dillo', 'Quadruplet_One', 'Stargazer', 'Clawer', 'Blizzard_Blown', 'Hairy_Screamer', 'Priodontes', 'Yepes_Mulita', 'Scout', 'Cold_Air_Blows_Hot', 'Bedazzled', 'Howler', 'Pichi_Reborn', 'Furball', 'Rory_McGrath', 'Alfred_Brehm', 'Lakshmi_Bai', 'Selma_Blair', 'Fafner_Pendragon', 'Walter_Raleigh', 'Arthur_Wellesley', 'Konrad_Zuse', 'Bernhard_Grzimek', 'Lee_Christmas', 'Phillip_Boa', 'Francisco_Coronado', 'all', 'gold', 'peasant', 'worker', 'soldier', 'archer', 'knight', 'elite_guard', 'pikeman', 'blessed_soldier', 'ghost_warrior', 'sailor', 'swordsman', 'crossbowman', 'elite_archer', 'angry_peasant', 'pirate', 'elf', 'spirit', 'undead', 'savage', 'skeleton', 'barbarian', 'wild_horse', 'riding_horse', 'warmount', 'winged_horse', 'nazgul', 'flotsam', 'battering_ram', 'catapult', 'siege_tower', 'ratspider_venom', 'lana_bark', 'avinia_leaf', 'spiny_root', 'farrenstone', 'yew', 'elfstone', 'mallorn_wood', 'pretus_bones', 'longbow', 'plate_armor', 'longsword', 'pike', 'ox', 'wood', 'stone', 'iron', 'leather', 'ratspider', 'mithril', 'gate_crystal', 'blank_scroll', 'crossbow', 'fish', 'opium', 'woven_basket', 'clay_pot', 'tax_cookie', 'drum', 'hide', 'mob_cookie', 'lead', 'pitch', 'centaur', 'minotaur', 'undead_cookie', 'fog_cookie', 'wind_cookie', 'rain_cookie', 'mage_menial_cookie', 'giant_spider', 'rat', 'lion', 'giant_bird', 'giant_lizard', 'bandit', 'chimera', 'harpie', 'dragon', 'orc', 'gorgon', 'wolf', 'crystal_orb', 'cyclops', 'giant', 'faery', 'petty_thief_cookie', 'hound', 'imperial_throne', 'crown_of_prosperity', 'skull_of_bastrestric', 'shipcraft', 'sailing', 'shipbuilding', 'fishing', 'combat', 'survive_fatal_wound', 'fight_to_the_death', 'construct_catapult', 'defense', 'archery', 'swordplay', 'weaponsmithing', 'stealth', 'petty_thievery', 'determine_inventory_of_character', 'determine_skills_of_character', "determine_character's_lord", 'conceal_faction', 'learn_of_richest_nearby_noble', 'torture_prisoner', 'sneak_into_structure', 'conceal_self', 'beastmastery', 'bird_spy', 'capture_beasts_in_battle', 'use_beasts_in_battle', 'breed_beasts', 'catch_wild_horses', 'train_wild_horse_to_riding_horse', 'train_wild_horse_to_warmount', 'summon_wild_men', 'persuade_wild_men_to_remain', 'breed_hound', 'persuasion', 'bribe_noble', 'persuade_oathbound_noble', 'raise_peasant_mob', 'rally_peasant_mob', 'incite_mob_violence', 'train_angry_peasants', 'construction', 'construct_siege_tower', 'stone_quarrying', 'alchemy', 'extract_venom_from_ratspider', 'make_potion_of_slavery', 'brew_healing_potion', 'brew_potion_of_death', 'record_skill_on_scroll', 'collect_rare_elements', 'turn_lead_into_gold', 'forestry', 'construct_battering_ram', 'harvest_lumber', 'harvest_yew', 'collect_rare_foliage', 'harvest_mallorn_wood', 'harvest_opium', 'improve_opium_production', 'mining', 'mine_iron', 'mine_gold', 'mine_mithril', 'trade', 'conceal_identity_of_trader', 'find_tradegood_for_sale', 'find_market_for_tradegood', 'religion', 'receive_vision', 'resurrect_dead_noble', 'preparatory_ritual', 'lay_to_rest', 'remove_blessing_from_soldiers', 'immunity_from_vision', 'magic', 'meditate', 'perform_common_tasks_for_gold', 'appear_common', 'view_current_aura_level_of_others', 'reveal_abilities_of_another_mage', 'tap_health_for_aura', 'heal', 'modern_magic_script', 'shroud_abilities_from_scry', 'detect_ability_scry', 'dispel_ability_shroud', 'advanced_meditation', 'hinder_meditation', 'weather_magic', 'fierce_wind', 'bind_storm_to_ship', 'scribe_weather_symbols', 'summon_rain', 'summon_wind', 'summon_fog', 'direct_storm', 'dissipate_storm', 'renew_storm_strength', 'lightning_bolt', 'seize_control_of_storm', 'fog_of_death', 'scrying', 'scry_location', 'shroud_location_from_magical_scry', 'dispel_location_shroud', 'ciphered_writing_of_areth-pirn', 'create_magical_barrier', 'remove_magical_barrier', 'locate_character', 'detect_location_scry', 'farcasting', 'save_farcast_state', 'banish_undead', 'gatecraft', 'teleport', 'detect_gates', 'jump_through_gate', 'seal_gate', 'unseal_gate_with_key', 'notify_if_gate_unsealed', 'forcefully_unseal_gate', 'reveal_gate_key', 'notify_of_gate_jumps', 'language_of_the_ancients', 'reverse_jump_through_gate', 'artifact_construction', 'forge_auraculum', 'reveal_creator_of_artifact', 'reveal_where_artifact_was_created', 'cloak_creator_of_artifact', 'cloak_region_of_artifact_creation', 'curse_noncreator_loyalty', 'forge_magical_weapon', 'forge_magical_armor', 'forge_magical_bow', 'dispel_cloaking_from_artifact', 'arcane_symbols', 'destroy_artifact', 'forge_palantir', 'necromancy', 'transcend_death', 'runes_of_evil', 'summon_ghost_warriors', 'raise_undead', 'summon_demon_lord', 'renew_demon_bond', 'banish_demon_lord', 'eating_of_the_dead', 'aura_blast', 'absorb_aura_blast', 'advanced_sorcery', 'trance', 'teleport_items']
# '_Ivory_Tower', '_Gulpers_Rock', '_Cave', have been manually added


reprocessordict = {
    "0":["all","item"],
    "1":["gold","item"],
    "10":["peasant","item"],
    "11":["worker","item"],
    "12":["soldier","item"],
    "13":["archer","item"],
    "14":["knight","item"],
    "15":["elite_guard","item"],
    "16":["pikeman","item"],
    "17":["blessed_soldier","item"],
    "18":["ghost_warrior","item"],
    "19":["sailor","item"],
    "20":["swordsman","item"],
    "21":["crossbowman","item"],
    "22":["elite_archer","item"],
    "23":["angry_peasant","item"],
    "24":["pirate","item"],
    "25":["elf","item"],
    "26":["spirit","item"],
    "31":["undead","item"],
    "32":["savage","item"],
    "33":["skeleton","item"],
    "34":["barbarian","item"],
    "51":["wild_horse","item"],
    "52":["riding_horse","item"],
    "53":["warmount","item"],
    "54":["winged_horse","item"],
    "55":["nazgul","item"],
    "59":["flotsam","item"],
    "60":["battering_ram","item"],
    "61":["catapult","item"],
    "62":["siege_tower","item"],
    "63":["ratspider_venom","item"],
    "64":["lana_bark","item"],
    "65":["avinia_leaf","item"],
    "66":["spiny_root","item"],
    "67":["farrenstone","item"],
    "68":["yew","item"],
    "69":["elfstone","item"],
    "70":["mallorn_wood","item"],
    "71":["pretus_bones","item"],
    "72":["longbow","item"],
    "73":["plate_armor","item"],
    "74":["longsword","item"],
    "75":["pike","item"],
    "76":["ox","item"],
    "77":["wood","item"],
    "78":["stone","item"],
    "79":["iron","item"],
    "80":["leather","item"],
    "81":["ratspider","item"],
    "82":["mithril","item"],
    "83":["gate_crystal","item"],
    "84":["blank_scroll","item"],
    "85":["crossbow","item"],
    "87":["fish","item"],
    "93":["opium","item"],
    "94":["woven_basket","item"],
    "95":["clay_pot","item"],
    "96":["tax_cookie","item"],
    "98":["drum","item"],
    "99":["hide","item"],
    "101":["mob_cookie","item"],
    "102":["lead","item"],
    "261":["pitch","item"],
    "271":["centaur","item"],
    "272":["minotaur","item"],
    "273":["undead_cookie","item"],
    "274":["fog_cookie","item"],
    "275":["wind_cookie","item"],
    "276":["rain_cookie","item"],
    "277":["mage_menial_cookie","item"],
    "278":["giant_spider","item"],
    "279":["rat","item"],
    "280":["lion","item"],
    "281":["giant_bird","item"],
    "282":["giant_lizard","item"],
    "283":["bandit","item"],
    "284":["chimera","item"],
    "285":["harpie","item"],
    "286":["dragon","item"],
    "287":["orc","item"],
    "288":["gorgon","item"],
    "289":["wolf","item"],
    "290":["crystal_orb","item"],
    "291":["cyclops","item"],
    "292":["giant","item"],
    "293":["faery","item"],
    "294":["petty_thief_cookie","item"],
    "295":["hound","item"],
    "401":["imperial_throne","item"],
    "402":["crown_of_prosperity","item"],
    "403":["skull_of_bastrestric","item"],

    # skills   
    "600":["shipcraft","skill"],
    "601":["sailing","skill"],
    "602":["shipbuilding","skill"],
    "603":["fishing","skill"],
    "610":["combat","skill"],
    "611":["survive_fatal_wound","skill"],
    "612":["fight_to_the_death","skill"],
    "613":["construct_catapult","skill"],
    "614":["defense","skill"],
    "615":["archery","skill"],
    "616":["swordplay","skill"],
    "617":["weaponsmithing","skill"],
    "630":["stealth","skill"],
    "631":["petty_thievery","skill"],
    "632":["determine_inventory_of_character","skill"],
    "633":["determine_skills_of_character","skill"],
    "634":["determine_character's_lord","skill"],
    "635":["conceal_faction","skill"],
    "636":["learn_of_richest_nearby_noble","skill"],
    "637":["torture_prisoner","skill"],
    "639":["sneak_into_structure","skill"],
    "641":["conceal_self","skill"],
    "650":["beastmastery","skill"],
    "651":["bird_spy","skill"],
    "652":["capture_beasts_in_battle","skill"],
    "653":["use_beasts_in_battle","skill"],
    "654":["breed_beasts","skill"],
    "655":["catch_wild_horses","skill"],
    "656":["train_wild_horse_to_riding_horse","skill"],
    "657":["train_wild_horse_to_warmount","skill"],
    "658":["summon_wild_men","skill"],
    "659":["persuade_wild_men_to_remain","skill"],
    "661":["breed_hound","skill"],
    "670":["persuasion","skill"],
    "671":["bribe_noble","skill"],
    "672":["persuade_oathbound_noble","skill"],
    "673":["raise_peasant_mob","skill"],
    "674":["rally_peasant_mob","skill"],
    "675":["incite_mob_violence","skill"],
    "676":["train_angry_peasants","skill"],
    "680":["construction","skill"],
    "681":["construct_siege_tower","skill"],
    "682":["stone_quarrying","skill"],
    "690":["alchemy","skill"],
    "691":["extract_venom_from_ratspider","skill"],
    "692":["make_potion_of_slavery","skill"],
    "693":["brew_healing_potion","skill"],
    "694":["brew_potion_of_death","skill"],
    "695":["record_skill_on_scroll","skill"],
    "696":["collect_rare_elements","skill"],
    "697":["turn_lead_into_gold","skill"],
    "700":["forestry","skill"],
    "701":["construct_battering_ram","skill"],
    "702":["harvest_lumber","skill"],
    "703":["harvest_yew","skill"],
    "704":["collect_rare_foliage","skill"],
    "705":["harvest_mallorn_wood","skill"],
    "706":["harvest_opium","skill"],
    "707":["improve_opium_production","skill"],
    "720":["mining","skill"],
    "721":["mine_iron","skill"],
    "722":["mine_gold","skill"],
    "723":["mine_mithril","skill"],
    "730":["trade","skill"],
    "731":["conceal_identity_of_trader","skill"],
    "732":["find_tradegood_for_sale","skill"],
    "733":["find_market_for_tradegood","skill"],
    "750":["religion","skill"],
    "751":["receive_vision","skill"],
    "752":["resurrect_dead_noble","skill"],
    "753":["preparatory_ritual","skill"],
    "754":["lay_to_rest","skill"],
    "755":["remove_blessing_from_soldiers","skill"],
    "756":["immunity_from_vision","skill"],
    "800":["magic","skill"],
    "801":["meditate","skill"],
    "802":["perform_common_tasks_for_gold","skill"],
    "803":["appear_common","skill"],
    "804":["view_current_aura_level_of_others","skill"],
    "805":["reveal_abilities_of_another_mage","skill"],
    "806":["tap_health_for_aura","skill"],
    "807":["heal","skill"],
    "808":["modern_magic_script","skill"],
    "809":["shroud_abilities_from_scry","skill"],
    "811":["detect_ability_scry","skill"],
    "812":["dispel_ability_shroud","skill"],
    "813":["advanced_meditation","skill"],
    "814":["hinder_meditation","skill"],
    "820":["weather_magic","skill"],
    "821":["fierce_wind","skill"],
    "822":["bind_storm_to_ship","skill"],
    "823":["scribe_weather_symbols","skill"],
    "824":["summon_rain","skill"],
    "825":["summon_wind","skill"],
    "826":["summon_fog","skill"],
    "827":["direct_storm","skill"],
    "828":["dissipate_storm","skill"],
    "829":["renew_storm_strength","skill"],
    "831":["lightning_bolt","skill"],
    "832":["seize_control_of_storm","skill"],
    "833":["fog_of_death","skill"],
    "840":["scrying","skill"],
    "841":["scry_location","skill"],
    "842":["shroud_location_from_magical_scry","skill"],
    "843":["dispel_location_shroud","skill"],
    "844":["ciphered_writing_of_areth-pirn","skill"],
    "845":["create_magical_barrier","skill"],
    "846":["remove_magical_barrier","skill"],
    "847":["locate_character","skill"],
    "848":["detect_location_scry","skill"],
    "849":["farcasting","skill"],
    "851":["save_farcast_state","skill"],
    "852":["banish_undead","skill"],
    "860":["gatecraft","skill"],
    "861":["teleport","skill"],
    "862":["detect_gates","skill"],
    "863":["jump_through_gate","skill"],
    "864":["seal_gate","skill"],
    "865":["unseal_gate_with_key","skill"],
    "866":["notify_if_gate_unsealed","skill"],
    "867":["forcefully_unseal_gate","skill"],
    "868":["reveal_gate_key","skill"],
    "869":["notify_of_gate_jumps","skill"],
    "871":["language_of_the_ancients","skill"],
    "872":["reverse_jump_through_gate","skill"],
    "880":["artifact_construction","skill"],
    "881":["forge_auraculum","skill"],
    "882":["reveal_creator_of_artifact","skill"],
    "883":["reveal_where_artifact_was_created","skill"],
    "884":["cloak_creator_of_artifact","skill"],
    "885":["cloak_region_of_artifact_creation","skill"],
    "886":["curse_noncreator_loyalty","skill"],
    "887":["forge_magical_weapon","skill"],
    "888":["forge_magical_armor","skill"],
    "889":["forge_magical_bow","skill"],
    "891":["dispel_cloaking_from_artifact","skill"],
    "892":["arcane_symbols","skill"],
    "893":["destroy_artifact","skill"],
    "894":["forge_palantir","skill"],
    "900":["necromancy","skill"],
    "901":["transcend_death","skill"],
    "902":["runes_of_evil","skill"],
    "903":["summon_ghost_warriors","skill"],
    "904":["raise_undead","skill"],
    "905":["summon_demon_lord","skill"],
    "906":["renew_demon_bond","skill"],
    "907":["banish_demon_lord","skill"],
    "908":["eating_of_the_dead","skill"],
    "909":["aura_blast","skill"],
    "911":["absorb_aura_blast","skill"],
    "920":["advanced_sorcery","skill"],
    "921":["trance","skill"],
    "922":["teleport_items","skill"]
        }


preprocessordict = {
    # locations, added manually
    "_Ivory_Tower":["8276","location"], # new
    "_Gulpers_Rock":["6766","location"], # new
    "_Cave":["n130","location"], # new
    
    # ALLIANCE NOBLES of turn 59
    "Boduognat":["7754","noble"],
    "Bullywug":["9770","noble"],
    "Beowulf":["6094","noble"],
    "Empirius":["3955","noble"],
    "Satyr":["9595","noble"],
    "Rudbert":["4794","noble"],
    "Bigstick":["7568","noble"],
    "Myka_Vykos":["5996","noble"],
    "Skullthumper":["4880","noble"],
    "Seven_fingers":["6862","noble"],
    "Igor_the_Bonegrinder":["3699","noble"],
    "Nepomucenos":["8176","noble"],
    "Paolo_Giovanni":["1577","noble"],
    "Mud":["2902","noble"],
    "Frikky":["3527","noble"],
    "Cain":["4180","noble"],
    "Snake":["1291","noble"],
    "Jinx":["3633","noble"],
    "Didude":["4455","noble"],
    "Banana_Nut":["6624","noble"],
    "Dronte":["7689","noble"],
    "Slook":["7311","noble"],
    "Dreg":["6338","noble"],
    "Hammer":["8258","noble"],
    "Eternal":["3683","noble"],
    "Bomber":["4988","noble"],
    "Sloth":["2415","noble"],
    "Glutony":["4164","noble"],
    "Envy":["7786","noble"],
    "Pride":["8073","noble"],
    "Wrath":["8143","noble"],
    "Passage":["6823","noble"],
    "Rebellion":["7508","noble"],
    "Bastard":["8864","noble"],
    "Greed":["7504","noble"],
    "Lust":["3284","noble"],
    "Rakharo":["9465","noble"],
    "Jhogo":["1295","noble"],
    "Jaehaerys_Targaryen":["7716","noble"],
    "Rhaegar_Targaryen":["2297","noble"],
    "Strong_Belwas":["5544","noble"],
    "Aerys_Targaryen":["8702","noble"],
    "Drogo":["6646","noble"],
    "Jorah_Mormont":["7161","noble"],
    "Arstan_Whitebeard":["7809","noble"],
    "Jaehaerys_Targaryen":["7116","noble"],
    "Daenarys_Targaryen":["6307","noble"],
    "Aegon_Targaryen":["6457","noble"],
    "Rhaenys_Targaryen":["6735","noble"],
    "Aemon_Targaryen":["6040","noble"],
    "Jhiqui":["4093","noble"],
    "Viserys_Targaryen":["7688","noble"],
    "Illyrio_Mopatis":["2782","noble"],
    "King_Bockor":["4175","noble"],
    "Grunk":["5539","noble"],
    "Braaggh":["8651","noble"],
    "Korgul":["4270","noble"],
    "Scrag":["6341","noble"],
    "Drakk":["7213","noble"],
    "Mord":["1276","noble"],
    "Karash":["5014","noble"],
    "Karak":["5118","noble"],
    "Murk":["4405","noble"],
    "Oomph":["2920","noble"],
    "Claw":["1251","noble"],
    "Gruumsh":["4720","noble"],
    "Krusk":["9264","noble"],
    "Azuul":["6169","noble"],
    "Harhar":["6992","noble"],
    "Ubada":["2875","noble"],
    "Munguk_the_giant":["1534","noble"],
    "Red_Kraken":["4221","noble"],
    "Primal_Freegrazer":["4830","noble"],
    "Yoshi_the_Gulper":["6406","noble"],
    "Nightfury":["4073","noble"],
    "Wolftail":["8942","noble"],
    "Mighty_Wings":["8079","noble"],
    "Doom_Dreadnaught":["6759","noble"],
    "White_Spear":["2107","noble"],
    "Horror_Show":["2200","noble"],
    "Mouth_of_the_Devourer":["2962","noble"],
    "Hard_Boiled":["5625","noble"],
    "Cat_of_Purr":["9515","noble"],
    "Black_Fangs":["5726","noble"],
    "Feathersnake":["5649","noble"],
    "Silent_Paw":["1592","noble"],
    "Yu-Yu_the_Gloater":["4471","noble"],
    "Totemizer":["7328","noble"],
    "Dangerlight":["7769","noble"],
    "Dread_Frog":["4535","noble"],
    "Painful_Death":["1216","noble"],
    "Souldrinker":["4478","noble"],
    "Grim_Reaper":["9145","noble"],
    "Pestilence":["9100","noble"],
    "Famine":["6893","noble"],
    "Conquest":["6102","noble"],
    "Satan's_Little_Helper_II":["9184","noble"],
    "War":["1233","noble"],
    "Satan's_Little_Helper":["6493","noble"],
    "Joris":["2330","noble"],
    "Piet":["3327","noble"],
    "David_Livingstone":["6923","noble"],
    "Walking_Death":["3825","noble"],
    "Ethan_Venge":["6910","noble"],
    "Drago_Spatz":["4625","noble"],
    "Sgt_York":["7558","noble"],
    "Karl_Meckler":["7763","noble"],
    "Jason_West":["6054","noble"],
    "Carey_Bridger":["3296","noble"],
    "John_Builder":["3246","noble"],
    "Harlan_Brenach":["4645","noble"],
    "Billy_Mack":["4363","noble"],
    "Joe_Fish":["3243","noble"],
    "Sgt_Rock":["8661","noble"],
    "Jim_Nance":["7432","noble"],
    "Yancy_James":["5393","noble"],
    "Ziggy_Stardust":["6612","noble"],
    "Jorj":["2791","noble"],
    "Godzilla":["1683","noble"],
    "Klaus":["1460","noble"],
    "Jimmy_Dean":["6111","noble"],
    "Emissary":["2880","noble"],
    "Pen":["9643","noble"],
    "Xen":["3053","noble"],
    "Dude":["8721","noble"],
    "Howl":["6991","noble"],
    "Hasan":["4744","noble"],
    "Talin":["6859","noble"],
    "Full_of_Hot_Air":["5905","noble"],
    "Seasick_dillo":["7908","noble"],
    "Quadruplet_One":["9805","noble"],
    "Stargazer":["2767","noble"],
    "Clawer":["5876","noble"],
    "Blizzard_Blown":["6009","noble"],
    "Hairy_Screamer":["5090","noble"],
    "Priodontes":["3059","noble"],
    "Yepes_Mulita":["3842","noble"],
    "Scout":["4361","noble"],
    "Cold_Air_Blows_Hot":["5066","noble"],
    "Bedazzled":["4934","noble"],
    "Howler":["6524","noble"],
    "Pichi_Reborn":["6219","noble"],
    "Furball":["5514","noble"],
    "Rory_McGrath":["4827","noble"],
    "Alfred_Brehm":["6235","noble"],
    "Lakshmi_Bai":["5094","noble"],
    "Selma_Blair":["9178","noble"],
    "Fafner_Pendragon":["5558","noble"],
    "Walter_Raleigh":["7331","noble"],
    "Arthur_Wellesley":["8378","noble"],
    "Konrad_Zuse":["8498","noble"],
    "Bernhard_Grzimek":["1418","noble"],
    "Lee_Christmas":["1429","noble"],
    "Phillip_Boa":["8167","noble"],
    "Francisco_Coronado":["1652","noble"],
    # END OF ALLIANCE NOBLES
    #items
    "all":["0","item"],
    "gold":["1","item"],
    "peasant":["10","item"],
    "worker":["11","item"],
    "soldier":["12","item"],
    "archer":["13","item"],
    "knight":["14","item"],
    "elite_guard":["15","item"],
    "pikeman":["16","item"],
    "blessed_soldier":["17","item"],
    "ghost_warrior":["18","item"],
    "sailor":["19","item"],
    "swordsman":["20","item"],
    "crossbowman":["21","item"],
    "elite_archer":["22","item"],
    "angry_peasant":["23","item"],
    "pirate":["24","item"],
    "elf":["25","item"],
    "spirit":["26","item"],
    "undead":["31","item"],
    "savage":["32","item"],
    "skeleton":["33","item"],
    "barbarian":["34","item"],
    "wild_horse":["51","item"],
    "riding_horse":["52","item"],
    "warmount":["53","item"],
    "winged_horse":["54","item"],
    "nazgul":["55","item"],
    "flotsam":["59","item"],
    "battering_ram":["60","item"],
    "catapult":["61","item"],
    "siege_tower":["62","item"],
    "ratspider_venom":["63","item"],
    "lana_bark":["64","item"],
    "avinia_leaf":["65","item"],
    "spiny_root":["66","item"],
    "farrenstone":["67","item"],
    "yew":["68","item"],
    "elfstone":["69","item"],
    "mallorn_wood":["70","item"],
    "pretus_bones":["71","item"],
    "longbow":["72","item"],
    "plate_armor":["73","item"],
    "longsword":["74","item"],
    "pike":["75","item"],
    "ox":["76","item"],
    "wood":["77","item"],
    "stone":["78","item"],
    "iron":["79","item"],
    "leather":["80","item"],
    "ratspider":["81","item"],
    "mithril":["82","item"],
    "gate_crystal":["83","item"],
    "blank_scroll":["84","item"],
    "crossbow":["85","item"],
    "fish":["87","item"],
    "opium":["93","item"],
    "woven_basket":["94","item"],
    "clay_pot":["95","item"],
    "tax_cookie":["96","item"],
    "drum":["98","item"],
    "hide":["99","item"],
    "mob_cookie":["101","item"],
    "lead":["102","item"],
    "pitch":["261","item"],
    "centaur":["271","item"],
    "minotaur":["272","item"],
    "undead_cookie":["273","item"],
    "fog_cookie":["274","item"],
    "wind_cookie":["275","item"],
    "rain_cookie":["276","item"],
    "mage_menial_cookie":["277","item"],
    "giant_spider":["278","item"],
    "rat":["279","item"],
    "lion":["280","item"],
    "giant_bird":["281","item"],
    "giant_lizard":["282","item"],
    "bandit":["283","item"],
    "chimera":["284","item"],
    "harpie":["285","item"],
    "dragon":["286","item"],
    "orc":["287","item"],
    "gorgon":["288","item"],
    "wolf":["289","item"],
    "crystal_orb":["290","item"],
    "cyclops":["291","item"],
    "giant":["292","item"],
    "faery":["293","item"],
    "petty_thief_cookie":["294","item"],
    "hound":["295","item"],
    "imperial_throne":["401","item"],
    #skills
    "shipcraft":["600","skill"],
    "sailing":["601","skill"],
    "shipbuilding":["602","skill"],
    "fishing":["603","skill"],
    "combat":["610","skill"],
    "survive_fatal_wound":["611","skill"],
    "fight_to_the_death":["612","skill"],
    "construct_catapult":["613","skill"],
    "defense":["614","skill"],
    "archery":["615","skill"],
    "swordplay":["616","skill"],
    "weaponsmithing":["617","skill"],
    "stealth":["630","skill"],
    "petty_thievery":["631","skill"],
    "determine_inventory_of_character":["632","skill"],
    "determine_skills_of_character":["633","skill"],
    "determine_character's_lord":["634","skill"],
    "conceal_faction":["635","skill"],
    "learn_of_richest_nearby_noble":["636","skill"],
    "torture_prisoner":["637","skill"],
    "sneak_into_structure":["639","skill"],
    "conceal_self":["641","skill"],
    "beastmastery":["650","skill"],
    "bird_spy":["651","skill"],
    "capture_beasts_in_battle":["652","skill"],
    "use_beasts_in_battle":["653","skill"],
    "breed_beasts":["654","skill"],
    "catch_wild_horses":["655","skill"],
    "train_wild_horse_to_riding_horse":["656","skill"],
    "train_wild_horse_to_warmount":["657","skill"],
    "summon_wild_men":["658","skill"],
    "persuade_wild_men_to_remain":["659","skill"],
    "breed_hound":["661","skill"],
    "bribe_noble":["671","skill"],
    "persuade_oathbound_noble":["672","skill"],
    "raise_peasant_mob":["673","skill"],
    "rally_peasant_mob":["674","skill"],
    "incite_mob_violence":["675","skill"],
    "train_angry_peasants":["676","skill"],
    "persuasion":["670","skill"],
    "bribe_noble":["671","skill"],
    "persuade_oathbound_noble":["672","skill"],
    "raise_peasant_mob":["673","skill"],
    "rally_peasant_mob":["674","skill"],
    "incite_mob_violence":["675","skill"],
    "train_angry_peasants":["676","skill"],
    "construction":["680","skill"],
    "construct_siege_tower":["681","skill"],
    "stone_quarrying":["682","skill"],
    "alchemy":["690","skill"],
    "extract_venom_from_ratspider":["691","skill"],
    "make_potion_of_slavery":["692","skill"],
    "brew_healing_potion":["693","skill"],
    "brew_potion_of_death":["694","skill"],
    "record_skill_on_scroll":["695","skill"],
    "collect_rare_elements":["696","skill"],
    "turn_lead_into_gold":["697","skill"],
    "forestry":["700","skill"],
    "construct_battering_ram":["701","skill"],
    "harvest_lumber":["702","skill"],
    "harvest_yew":["703","skill"],
    "collect_rare_foliage":["704","skill"],
    "harvest_mallorn_wood":["705","skill"],
    "harvest_opium":["706","skill"],
    "improve_opium_production":["707","skill"],
    "mining":["720","skill"],
    "mine_iron":["721","skill"],
    "mine_gold":["722","skill"],
    "mine_mithril":["723","skill"],
    "trade":["730","skill"],
    "conceal_identity_of_trader":["731","skill"],
    "find_tradegood_for_sale":["732","skill"],
    "find_market_for_tradegood":["733","skill"],
    "religion":["750","skill"],
    "receive_vision":["751","skill"],
    "resurrect_dead_noble":["752","skill"],
    "preparatory_ritual":["753","skill"],
    "lay_to_rest":["754","skill"],
    "remove_blessing_from_soldiers":["755","skill"],
    "immunity_from_vision":["756","skill"],
    "magic":["800","skill"],
    "meditate":["801","skill"],
    "perform_common_tasks_for_gold":["802","skill"],
    "appear_common":["803","skill"],
    "view_current_aura_level_of_others":["804","skill"],
    "reveal_abilities_of_another_mage":["805","skill"],
    "tap_health_for_aura":["806","skill"],
    "heal":["807","skill"],
    "modern_magic_script":["808","skill"],
    "shroud_abilities_from_scry":["809","skill"],
    "detect_ability_scry":["811","skill"],
    "dispel_ability_shroud":["812","skill"],
    "advanced_meditation":["813","skill"],
    "hinder_meditation":["814","skill"],
    "weather_magic":["820","skill"],
    "fierce_wind":["821","skill"],
    "bind_storm_to_ship":["822","skill"],
    "scribe_weather_symbols":["823","skill"],
    "summon_rain":["824","skill"],
    "summon_wind":["825","skill"],
    "summon_fog":["826","skill"],
    "direct_storm":["827","skill"],
    "dissipate_storm":["828","skill"],
    "renew_storm_strength":["829","skill"],
    "lightning_bolt":["831","skill"],
    "seize_control_of_storm":["832","skill"],
    "fog_of_death":["833","skill"],
    "scrying":["840","skill"],
    "scry_location":["841","skill"],
    "shroud_location_from_magical_scry":["842","skill"],
    "dispel_location_shroud":["843","skill"],
    "ciphered_writing_of_areth-pirn":["844","skill"],
    "create_magical_barrier":["845","skill"],
    "remove_magical_barrier":["846","skill"],
    "locate_character":["847","skill"],
    "detect_location_scry":["848","skill"],
    "farcasting":["849","skill"],
    "save_farcast_state":["851","skill"],
    "banish_undead":["852","skill"],
    "gatecraft":["860","skill"],
    "teleport":["861","skill"],
    "detect_gates":["862","skill"],
    "jump_through_gate":["863","skill"],
    "seal_gate":["864","skill"],
    "unseal_gate_with_key":["865","skill"],
    "notify_if_gate_unsealed":["866","skill"],
    "forcefully_unseal_gate":["867","skill"],
    "reveal_gate_key":["868","skill"],
    "notify_of_gate_jumps":["869","skill"],
    "language_of_the_ancients":["871","skill"],
    "reverse_jump_through_gate":["872","skill"],
    "artifact_construction":["880","skill"],
    "forge_auraculum":["881","skill"],
    "reveal_creator_of_artifact":["882","skill"],
    "reveal_where_artifact_was_created":["883","skill"],
    "cloak_creator_of_artifact":["884","skill"],
    "cloak_region_of_artifact_creation":["885","skill"],
    "curse_noncreator_loyalty":["886","skill"],
    "forge_magical_weapon":["887","skill"],
    "forge_magical_armor":["888","skill"],
    "forge_magical_bow":["889","skill"],
    "dispel_cloaking_from_artifact":["891","skill"],
    "arcane_symbols":["892","skill"],
    "destroy_artifact":["893","skill"],
    "forge_palantir":["894","skill"],
    "necromancy":["900","skill"],
    "transcend_death":["901","skill"],
    "runes_of_evil":["902","skill"],
    "summon_ghost_warriors":["903","skill"],
    "raise_undead":["904","skill"],
    "summon_demon_lord":["905","skill"],
    "renew_demon_bond":["906","skill"],
    "banish_demon_lord":["907","skill"],
    "eating_of_the_dead":["908","skill"],
    "aura_blast":["909","skill"],
    "absorb_aura_blast":["911","skill"],
    "advanced_sorcery":["920","skill"],
    "trance":["921","skill"],
    "teleport_items":["922","skill"]

  

    }







def processstring(astring):
    """processes a string"""
    print astring+" --> ",
    alist = astring.split(" ")
    newlist = []


    for item in alist:
        print "processing item: "+str(item)+" ",
        if item in preprocessordict.keys():
                print "is in dict."
                # the skill is either researched. No use needed.
                newlist.append(preprocessordict[item][0])
        else:
            print "is not in dict."
            newlist.append(item)


    for item in newlist:
        print item,
    print

# Hmm. Orders need to be parsed. So an order checker is in place.


if __name__ == '__main__':

    testing = 0
    if testing == 1:
        processstring("Hello")
        processstring("give 9394 peasant all")
        processstring("use receive_vision 3849")
        processstring("study stealth 10")
        processstring("use conceal_self 1")
        processstring("use fight_to_the_death 1")
        processstring("Mouth_of_the_Devourer")
        processstring("study breed_hound")

        # more tests..

        print str(preprocessordict["breed_hound"])




    manual = 0
    if manual == 1:

        for i in range(0,1000):
            if str(i) in reprocessordict:
                print reprocessordict[str(i)][1]+" "+str(i)+" "+reprocessordict[str(i)][0]
        



    compile_aliasorderlist = 1
    
    if compile_aliasorderlist == 1:
        
        orderaliaslist = ['accept', 'admit', 'attack', 'banner', 'behind', 'board', 'bribe', 'breed', 'build', 'buy', 'catch', 'claim', 'collect', 'contact', 'decree', 'default', 'defend', 'die', 'drop', 'email', 'execute', 'exhume', 'explore', 'fee', 'ferry', 'fish', 'flag', 'fly', 'forget', 'form', 'format', 'garrison', 'get', 'give', 'guard', 'honor', 'hostile', 'improve', 'lore', 'make', 'message', 'move', 'name', 'neutral', 'notab', 'oath', 'password', 'pay', 'pillage', 'players', 'pledge', 'post', 'press', 'promote', 'public', 'quarry', 'quest', 'quit', 'raze', 'recruit', 'repair', 'research', 'resend', 'rumor', 'sail', 'seek', 'sell', 'sneak', 'stack', 'stop', 'study', 'surrender', 'take', 'terrorize', 'train', 'ungarrison', 'unload', 'unstack', 'use', 'vis_email', 'wait']
        # print len(orderaliaslist)
        waitcommandlist = ['clear', 'day', 'turn', 'ferry', 'flag', 'fog', 'item', 'loc', 'not', 'owner', 'rain', 'ship', 'shiploc', 'stack', 'time', 'top', 'unit', 'wind']
        directionslist = ['n','north','s','south','w','west','e','east','in','out']
        nobleslist = ['Boduognat', 'Bullywug', 'Beowulf', 'Empirius', 'Satyr', 'Rudbert', 'Bigstick', 'Myka_Vykos', 'Skullthumper', 'Seven_fingers', 'Igor_the_Bonegrinder', 'Nepomucenos', 'Paolo_Giovanni', 'Mud', 'Frikky', 'Cain', 'Snake', 'Jinx', 'Didude', 'Banana_Nut', 'Dronte', 'Slook', 'Dreg', 'Hammer', 'Eternal', 'Bomber', 'Sloth', 'Glutony', 'Envy', 'Pride', 'Wrath', 'Passage', 'Rebellion', 'Bastard', 'Greed', 'Lust', 'Rakharo', 'Jhogo', 'Jaehaerys_Targaryen', 'Rhaegar_Targaryen', 'Strong_Belwas', 'Aerys_Targaryen', 'Drogo', 'Jorah_Mormont', 'Arstan_Whitebeard', 'Jaehaerys_Targaryen', 'Daenarys_Targaryen', 'Aegon_Targaryen', 'Rhaenys_Targaryen', 'Aemon_Targaryen', 'Jhiqui', 'Viserys_Targaryen', 'Illyrio_Mopatis', 'King_Bockor', 'Grunk', 'Braaggh', 'Korgul', 'Scrag', 'Drakk', 'Mord', 'Karash', 'Karak', 'Murk', 'Oomph', 'Claw', 'Gruumsh', 'Krusk', 'Azuul', 'Harhar', 'Ubada', 'Munguk_the_giant', 'Red_Kraken', 'Primal_Freegrazer', 'Yoshi_the_Gulper', 'Nightfury', 'Wolftail', 'Mighty_Wings', 'Doom_Dreadnaught', 'White_Spear', 'Horror_Show', 'Mouth_of_the_Devourer', 'Hard_Boiled', 'Cat_of_Purr', 'Black_Fangs', 'Feathersnake', 'Silent_Paw', 'Yu-Yu_the_Gloater', 'Totemizer', 'Dangerlight', 'Dread_Frog', 'Painful_Death', 'Souldrinker', 'Grim_Reaper', 'Pestilence', 'Famine', 'Conquest', "Satan's_Little_Helper_II", 'War', "Satan's_Little_Helper", 'Joris', 'Piet', 'David_Livingstone', 'Walking_Death', 'Ethan_Venge', 'Drago_Spatz', 'Sgt_York', 'Karl_Meckler', 'Jason_West', 'Carey_Bridger', 'John_Builder', 'Harlan_Brenach', 'Billy_Mack', 'Joe_Fish', 'Sgt_Rock', 'Jim_Nance', 'Yancy_James', 'Ziggy_Stardust', 'Jorj', 'Godzilla', 'Klaus', 'Jimmy_Dean', 'Emissary', 'Pen', 'Xen', 'Dude', 'Howl', 'Hasan', 'Talin', 'Full_of_Hot_Air', 'Seasick_dillo', 'Quadruplet_One', 'Stargazer', 'Clawer', 'Blizzard_Blown', 'Hairy_Screamer', 'Priodontes', 'Yepes_Mulita', 'Scout', 'Cold_Air_Blows_Hot', 'Bedazzled', 'Howler', 'Pichi_Reborn', 'Furball', 'Rory_McGrath', 'Alfred_Brehm', 'Lakshmi_Bai', 'Selma_Blair', 'Fafner_Pendragon', 'Walter_Raleigh', 'Arthur_Wellesley', 'Konrad_Zuse', 'Bernhard_Grzimek', 'Lee_Christmas', 'Phillip_Boa', 'Francisco_Coronado']
        aliaslist = orderaliaslist
        aliaslist.extend(waitcommandlist)
        aliaslist.extend(directionslist)
        aliaslist.extend(nobleslist)
        print "Lists extended.."
        
        
        print "complete command alias list for Olympia G3:"
        print aliaslist





# study research order checker can be easy I.e. must be of study XXX code and may habe a second paramter
# give order can be checked in similar way.
# How can this be done? Include arguments in a third list element and check it?

#distinguish between item and troop and beast
# give all could check the inventory line, or even read in the turn report to be smarter.

# specials:
#   giveall_riding
#   giveall_humans
#   giveall_beasts
    
